openapi: '3.0.2'
info:
  title: Category Open API GO-PZN
  version: '1.0'
servers:
  - url: http://localhost:3000/api
paths:
  /categories: 
    get: 
      tags: [Category]
      security:
        - CategoryAuth: []
      description: List All Categories
      summary: List All Categories
      responses: 
        200: 
          description: Success get Categories
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Categories'
    post: 
      tags: [Category]
      security:
        - CategoryAuth: []
      description: 'Create Categories'
      summary: Create Categories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUpdateCategories"
      responses: 
        200:
          description: Success create category
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Categories'
  /categories/{categoriesId}:
    get:
      description: 'Get Categories by Id'
      security:
        - CategoryAuth: []
      tags:
        - "Category"
      parameters:
        - in: path
          name: "categoriesId"
          schema:
            type: integer
          required: true
          description: categoriesId must be numberic
      responses:
        '200':
          description: "Success get category"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Categories'
    put:
      description: 'Update Data Category by id'
      security:
        - CategoryAuth: []
      tags:
        - "Category"
      parameters:
        - in: path
          name: "categoriesId"
          schema: 
            type: integer
          required: true
          description: categoriesId must be numberic
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUpdateCategories"
      responses:
        '200':
          description: OK
    delete:
      description: 'delete data category by id'
      security:
        - CategoryAuth: []
      tags:
        - "Category"
      parameters:
        - in: path
          name: "categoriesId"
          schema:
            type: string
          required: true
      responses:
        '200':
          description: "Success delete data category"
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: number
components:
  securitySchemes:
    CategoryAuth:
      type: apiKey
      name: X-API-KEY
      in: header
      description: "Authentication for category api"
  schemas:
    CreateUpdateCategories:
      type: object
      properties:
        name: 
          type: string
    Categories:
      type: object
      properties:
        code: 
          type: number
        status: 
          type: number
        data:
          type: array
          items: 
            type: object
            properties:
              id: 
                type: number
              name:
                type: string
