### Get all category
DELETE http://localhost:3000/api/categories
Accept: application/json

### Create new category
POST http://localhost:3000/api/categories
Accept: application/json
Content-Type: application/json

{
    "Name":"Book"
}

###Get Category By Id
GET http://localhost:3000/api/categories/5
Accept: application/json

### Update data category by id
PUT http://localhost:3000/api/categories/6 HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "Name":"Fashion"
}

### Delete data category by id
DELETE http://localhost:3000/api/categories/7 HTTP/1.1
Accept: application/json
Content-Type: application/json